apiVersion: v1
kind: Namespace
metadata:
  name: paas-webhooks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: privileged-kata-containers-webhook-controller-manager
  namespace: paas-webhooks
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: privileged-kata-containers-webhook-leader-election-role
  namespace: paas-webhooks
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: privileged-kata-containers-webhook-leader-election-rolebinding
  namespace: paas-webhooks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: privileged-kata-containers-webhook-leader-election-role
subjects:
- kind: ServiceAccount
  name: privileged-kata-containers-webhook-controller-manager
  namespace: paas-webhooks
---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: ea97f992.paas.il
kind: ConfigMap
metadata:
  name: privileged-kata-containers-webhook-manager-config
  namespace: paas-webhooks
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: privileged-kata-containers-webhook-server-cert
  name: privileged-kata-containers-webhook-service
  namespace: paas-webhooks
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: privileged-kata-containers-webhook-controller-manager
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: privileged-kata-containers-webhook-controller-manager
  name: privileged-kata-containers-webhook-controller-manager
  namespace: paas-webhooks
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: privileged-kata-containers-webhook-controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: privileged-kata-containers-webhook-controller-manager
    spec:
      containers:
      - args:
        - --leader-elect
        command:
        - /manager
        env:
        - name: VALID_KATA_IMAGES
          value: '["nginx:1.14.1", "nginx:1.14.2"]'
        image: docker.io/paasteam324/privileged-kata-containers-webhook:0.0.1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      securityContext:
        runAsNonRoot: true
      serviceAccountName: privileged-kata-containers-webhook-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: privileged-kata-containers-webhook-server-cert
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  creationTimestamp: null
  name: privileged-kata-containers-webhook-privileged-kata-containers-webhook-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ""
    service:
      name: privileged-kata-containers-webhook-service
      namespace: paas-webhooks
      path: /kata-runtime-builder-pod-mutation
  failurePolicy: Fail
  name: mkatapod.kb.io
  objectSelector:
    matchExpressions:
    - key: openshift.io/build.name
      operator: Exists
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
  creationTimestamp: null
  name: privileged-kata-containers-webhook-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: ""
    service:
      name: privileged-kata-containers-webhook-service
      namespace: paas-webhooks
      path: /validate-pod
  failurePolicy: Fail
  name: vkatapod.kb.io
  objectSelector:
    matchLabels:
      docker-builds: "true"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
  sideEffects: None
