apiVersion: v1
kind: Pod
metadata:
  labels:
    openshift.io/build.name: builder
  name: builder
  namespace: test
  ownerReferences:
  - apiVersion: build.openshift.io/v1
    kind: Build
    name: builder
    uid: aa28a635-1a6d-4986-8f02-3fd2893f8b50
    controller: true
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    securityContext:
      privileged: true
    ports:
    - containerPort: 80
    volumeMounts:
    - name: host
      mountPath: /host
    - name: buildworkdir
      mountPath: /buildworkdir
    - name: container-storage-root
      mountPath: /container-storage-root
    - name: config
      mountPath: /var/lib/kubelet/config.json
  volumes:
  - name: host
    hostPath:
      path: /
      type: ''
  - name: buildworkdir
    emptyDir: {}
  - name: container-storage-root
    emptyDir: {}
  - name: config
    hostPath:
      path: /var/lib/kubelet/config.json
      type: File