apiVersion: v1
kind: Pod
metadata:
  labels:
    docker-builds: "true"
  name: valid-privileged
  namespace: test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    securityContext:
      privileged: true
    ports:
    - containerPort: 80